#!/bin/bash
#############################################################################
# Copyright (c): 2021-2025, Huawei Tech. Co., Ltd.
# FileName     : ssh-keyscan
# Date         : 2024-05-18
#############################################################################
export LD_LIBRARY_PATH=/usr/lib64 && /usr/bin/ssh-keyscan "$@"